[build]
  publish = "dist"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[dev]
  command = "pnpm run dev"
  port = 5000
  publish = "dist"

# Generated redirects from content aliases
# Generated redirects from content aliases
# Generated redirects from content aliases
# Generated redirects from content aliases
# Generated redirects from content aliases
# Generated redirects from content aliases
# Generated redirects from content aliases
[[redirects]]
  from = "/about-me"
  to = "/about"
  status = 301

[[redirects]]
  from = "/about-us"
  to = "/about"
  status = 301

[[redirects]]
  from = "/contact-me"
  to = "/contact"
  status = 301

[[redirects]]
  from = "/contact-us"
  to = "/contact"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404